### ISSUE TITLE
Add pre-commit support to the project with GitHub Actions

### ISSUE THREAD

**Issue by gridhead** [gridhead/protop2g#12]
The project currently uses a makeshift code quality-checking script which can be found here https://github.com/gridhead/protop2g/blob/main/doformat.sh.

We can definitely be benefitted by the use of a more dedicated pre-commit support that not only allows us to confirm the code quality but also can run as checks with GitHub Actions.

**Comment by onuralpszr** [comment]
Complete by https://github.com/gridhead/protop2g/pull/13
